name: "compile tex to PDF"

on:
  push:
    paths:
      - "tex/resume.tex"
      - ".github/workflows/compileTex.yml"

jobs:
  # compile .tex
  compileTex:
    name: "compile .tex"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        name: "check out repo"

      - run: "ls -a ./tex"
        name: "check tex/ subdir"

      - uses: "xu-cheng/texlive-action/full@v1"
        name: "compile tex in docker"
        with:
          run: |
            cd tex/
            latexmk -xelatex resume.tex

      - name: "commit pdf"
        run: |
          git config --global user.name 'Luc Blassel'
          git config --global user.email 'luc.blassel@gmail.com'
          git add tex/resume.pdf
          git commit -m "creating .pdf"
          git push
