name: "create and render PDF"

on:
  push:
    paths: 
      - "resume.json"
      - ".github/workflows/*"

jobs:

  # Make .tex file from .json format
  makeTex:
    name: "make .tex"
    runs-on: "ubuntu-latest"
    steps:

      - uses: actions/checkout@v2
        name: "checkout repo"

      - uses: actions/setup-python@v2
        name: "set up python"
        with:
          python-version: "3.8"
          architecture: "x64"

      - run: "python ./scripts/convertToTex.py --input resume.json --output tex/resume.tex"
        name: "generate .tex file"

      - name: "commit tex file"
        run: |
          git config --global user.name 'Luc Blassel'
          git config --global user.email 'luc.blassel@gmail.com'
          git add tex/resume.tex
          git commit -m "creating .tex"
          git push
  
  # compile .tex
  compileTex:
    name: "compile .tex"
    needs: makeTex
    runs-on: "ubuntu-latest"
    container: "blang/latex:ctanfull"
    steps: 
      - uses: actions/checkout@v2
        name: "check out repo"

      - run: "cd ./tex && pwd && ls -a"
        name: "go to subdir"

      - run: "latexmk -xelatex resume.tex"
        name: "compile tex in docker"

      - name: "commit pdf"
        run: |
          git config --global user.name 'Luc Blassel'
          git config --global user.email 'luc.blassel@gmail.com'
          git add tex/resume.pdf
          git commit -m "creating .pdf"
          git push


