name: "create Tex file"

on:
  push:
    paths:
      - "resume.json"
      - ".github/workflows/makeTex.yml"
      - "scripts/convertToTex.py"

jobs:
  # Make .tex file from .json format
  makeTex:
    name: "make .tex"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        name: "checkout repo"

      - uses: actions/setup-python@v2
        name: "set up python"
        with:
          python-version: "3.8"
          architecture: "x64"

      - run: "python ./scripts/convertToTex.py --input resume.json --output tex/resume.tex"
        name: "generate .tex file"

      - name: "commit tex file"
        run: bash ./scripts/commitChanges.sh tex/resume.tex
  
  # compile .tex file
  compileTex:
    name: "compile .tex"
    runs-on: "ubuntu-latest"
    needs: makeTex
    steps:
      - uses: actions/checkout@v2
        name: "check out repo"

      - run: "ls -a ./tex"
        name: "check tex/ subdir"

      - uses: "xu-cheng/texlive-action/full@v1"
        name: "compile tex in docker"
        with:
          run: |
            cd tex/
            latexmk -xelatex resume.tex

      - name: "commit pdf file"
        run: ./scripts/commitChanges tex/resume.pdf
